import React from 'react';
import { ShieldCheck, ShieldAlert, Cpu, Eye, FileText, ArrowRight } from 'lucide-react';

const Home = ({ setActiveTab }) => {
  return (
    <div className="space-y-8 animate-fade-in max-w-5xl mx-auto py-4">
      {/* Hero Welcome banner */}
      <div className="glass-panel p-8 relative overflow-hidden bg-gradient-to-r from-slate-950 via-slate-900/60 to-slate-950">
        <div className="absolute top-0 right-0 w-96 h-96 bg-cyber-primary/5 rounded-full filter blur-3xl -z-10 translate-x-20 -translate-y-20 animate-pulse-slow" />
        <div className="space-y-4 max-w-3xl">
          <span className="text-xs font-mono text-cyber-primary uppercase tracking-widest bg-cyber-primary/10 px-3 py-1 rounded-full border border-cyber-primary/30">
            SYSTEM MISSION BRIEFING
          </span>
          <h1 className="text-4xl font-extrabold text-white font-sans tracking-wide leading-tight">
            Explainable AI Framework for Detecting Generative Steganography
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed font-sans">
            X-StegDetect is a digital forensic analysis platform designed to detect steganographic payloads generated by the state-of-the-art <strong>ViT-DiffSteg</strong> (Vision Transformer and Diffusion model) embedding systems. Using multi-model architectures and Explainable AI, the system isolates pixel-level modifications and maps mathematical attributions to provide evidence for cybersecurity investigations.
          </p>
          <div className="pt-4">
            <button
              onClick={() => setActiveTab('detection')}
              className="neon-btn-primary flex items-center space-x-2 px-6 py-3"
            >
              <span>ACCESS DETECTION LAB</span>
              <ArrowRight className="h-4.5 w-4.5" />
            </button>
          </div>
        </div>
      </div>

      {/* Main Pillars Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card flex flex-col justify-between">
          <div className="space-y-3">
            <div className="p-3 bg-cyber-primary/10 rounded-lg text-cyber-primary inline-block">
              <Cpu className="h-6 w-6" />
            </div>
            <h3 className="text-base font-bold text-white tracking-wide">Dynamic Ensemble Classifiers</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Evaluate image textures across four distinct architectures: ResNet50, EfficientNet-B0, ViT-B/16, and Swin-T. Run single modes or configure coalition ensembles using soft, majority, or weighted voting strategies.
            </p>
          </div>
        </div>

        <div className="glass-card flex flex-col justify-between">
          <div className="space-y-3">
            <div className="p-3 bg-cyber-secondary/10 rounded-lg text-cyber-secondary inline-block">
              <Eye className="h-6 w-6" />
            </div>
            <h3 className="text-base font-bold text-white tracking-wide">Explainable AI Attributions</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Drill down into predictions using three layers of XAI. Verify activations with Grad-CAM, compute Shapley coalition weights using optimized superpixel SHAP, and list LIME pixel regression evidence.
            </p>
          </div>
        </div>

        <div className="glass-card flex flex-col justify-between">
          <div className="space-y-3">
            <div className="p-3 bg-rose-500/10 rounded-lg text-cyber-accent inline-block">
              <FileText className="h-6 w-6" />
            </div>
            <h3 className="text-base font-bold text-white tracking-wide">Forensic PDF compilation</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Generate PDF digital forensic reports directly from the active analysis. Reports bundle case UUID markers, full metadata arrays, residual maps, and all XAI attribution diagrams into an investigation log.
            </p>
          </div>
        </div>
      </div>

      {/* Deep Technical Overview Section */}
      <div className="glass-panel p-6">
        <h3 className="text-sm font-mono text-slate-300 border-b border-slate-900 pb-3 uppercase tracking-wider mb-4">
          TECHNICAL CONTEXT: ViT-DiffSteg & GENERATIVE STEGANOGRAPHY
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
          <div className="space-y-3 text-xs text-slate-400 leading-relaxed font-mono">
            <p>
              Traditional steganography hiding techniques (e.g. LSB replacement, HUGO, S-UNIWARD) insert secret messages in the spatial or frequency components of a cover image, leaving subtle statistical shifts (higher spatial noise).
            </p>
            <p>
              Modern generative steganography platforms like <strong>ViT-DiffSteg</strong> leverage Vision Transformers paired with latent diffusion structures. Instead of modifying pixels directly, they map payloads into noise vectors during reverse diffusion sampling. The resulting stego image mirrors natural structural details, making detection extremely challenging for normal detectors.
            </p>
            <p>
              X-StegDetect resolves this by loading Transformer models fine-tuned to capture the shifted token representations and multi-scale frequency anomalies.
            </p>
          </div>
          
          <div className="bg-slate-950 border border-slate-900 rounded-lg p-5 space-y-4">
            <span className="text-[10px] font-mono text-slate-500 uppercase block border-b border-slate-900 pb-2">
              Forensic Workflow pipeline
            </span>
            <div className="flex flex-col space-y-2 text-xs font-mono">
              <div className="flex items-center space-x-3 p-2 bg-slate-900 rounded border border-slate-800">
                <span className="h-5 w-5 bg-cyber-primary/20 text-cyber-primary rounded-full flex items-center justify-center font-bold">1</span>
                <span className="text-slate-300">File Integrity & Format Validations</span>
              </div>
              <div className="flex items-center space-x-3 p-2 bg-slate-900 rounded border border-slate-800">
                <span className="h-5 w-5 bg-cyber-primary/20 text-cyber-primary rounded-full flex items-center justify-center font-bold">2</span>
                <span className="text-slate-300">Spatial Residual Analysis Filters</span>
              </div>
              <div className="flex items-center space-x-3 p-2 bg-slate-900 rounded border border-slate-800">
                <span className="h-5 w-5 bg-cyber-primary/20 text-cyber-primary rounded-full flex items-center justify-center font-bold">3</span>
                <span className="text-slate-300">PyTorch Classifier Inference Ensemble</span>
              </div>
              <div className="flex items-center space-x-3 p-2 bg-slate-900 rounded border border-slate-800">
                <span className="h-5 w-5 bg-cyber-primary/20 text-cyber-primary rounded-full flex items-center justify-center font-bold">4</span>
                <span className="text-slate-300">Attribution Mapping (Grad-CAM/SHAP/LIME)</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
