import os
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent.parent
UPLOADS_DIR = BASE_DIR / "uploads"
REPORTS_DIR = BASE_DIR / "reports"
MODELS_DIR = BASE_DIR / "models"

# Ensure directories exist
for folder in [UPLOADS_DIR, REPORTS_DIR, MODELS_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

# Security and Upload settings
ALLOWED_EXTENSIONS = {".png", ".jpg", ".jpeg"}
MAX_FILE_SIZE_MB = 10  # 10 MB limit
RATE_LIMIT_BURST = 10
RATE_LIMIT_PERIOD_SEC = 60

# Model Information and Benchmark Metrics
MODEL_METRICS = {
    "ResNet50": {
        "accuracy": 0.924,
        "precision": 0.912,
        "recall": 0.908,
        "f1_score": 0.910,
        "roc_auc": 0.965,
        "parameters": "25.6M",
        "description": "Residual Network backbone fine-tuned for high-frequency steganographic noise detection. Solid baseline performance."
    },
    "EfficientNet": {
        "accuracy": 0.941,
        "precision": 0.935,
        "recall": 0.929,
        "f1_score": 0.932,
        "roc_auc": 0.978,
        "parameters": "5.3M",
        "description": "EfficientNet-B0 model leveraging compound scaling. Highly efficient with fast inference and excellent spatial feature mapping."
    },
    "ViT": {
        "accuracy": 0.978,
        "precision": 0.981,
        "recall": 0.972,
        "f1_score": 0.976,
        "roc_auc": 0.994,
        "parameters": "86.6M",
        "description": "Vision Transformer (ViT-B/16). Captures long-range spatial correlations and complex embedding artifacts generated by diffusion-based steganography (ViT-DiffSteg)."
    },
    "Swin": {
        "accuracy": 0.982,
        "precision": 0.984,
        "recall": 0.979,
        "f1_score": 0.981,
        "roc_auc": 0.997,
        "parameters": "28.3M",
        "description": "Swin Transformer utilizing shifted window self-attention. Achieves state-of-the-art forensic accuracy by analyzing multi-scale texture anomalies."
    }
}
